# Modul 5
## Author: LiR
### Date : 24-12-2025

In [2]:
# проверяем где установлен
get_ipython().system('pip install pycoingecko')
import sys
!{sys.executable} -m pip install pycoingecko
from pycoingecko import CoinGeckoAPI

#import sys
print(sys.executable)
#!which pip      # Linux / Mac
!where pip      # Windows

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycoingecko in c:\users\rusla\appdata\roaming\python\python311\site-packages (3.2.0)
Requirement already satisfied: requests in c:\dev_soft\anaconda3_2023\lib\site-packages (from pycoingecko) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\dev_soft\anaconda3_2023\lib\site-packages (from requests->pycoingecko) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\dev_soft\anaconda3_2023\lib\site-packages (from requests->pycoingecko) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\dev_soft\anaconda3_2023\lib\site-packages (from requests->pycoingecko) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\dev_soft\anaconda3_2023\lib\site-packages (from requests->pycoingecko) (2025.10.5)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycoingecko in c:\users\rusla\appdata\roaming\python\python311\site-packages (3.2.0)
Requirement already satisfied: requests in c:\dev_soft\anaconda3_2023\lib\site-packages (from pycoingecko) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\dev_soft\anaconda3_2023\lib\site-packages (from requests->pycoingecko) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\dev_soft\anaconda3_2023\lib\site-packages (from requests->pycoingecko) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\dev_soft\anaconda3_2023\lib\site-packages (from requests->pycoingecko) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\dev_soft\anaconda3_2023\lib\site-packages (from requests->pycoingecko) (2025.10.5)
c:\dev_soft\anaconda3_2023\python.exe
C:\dev_soft\anaconda3_2023\Scripts\pip.exe

INFO: Could not find "#".
INFO: Could not find "Windows".

In [1]:
#!pip install pycoingecko
from pycoingecko import CoinGeckoAPI

cg = CoinGeckoAPI()
print(cg.ping())

{'gecko_says': '(V3) To the Moon!'}

In [2]:
#!pip install pycoingecko

from pycoingecko import CoinGeckoAPI

cg = CoinGeckoAPI()

bitcoin_data = cg.get_coin_market_chart_by_id(
    id='bitcoin',
    vs_currency='usd',
    days=30
)

bitcoin_data

{'prices': [[1763985712847, 86268.29336648472],
  [1763989255710, 85957.05408472917],
  [1763992837688, 86269.6656515316],
  [1763996558643, 86192.31160547498],
  [1764000097296, 86425.72745227045],
  [1764003728033, 87219.59492448122],
  [1764007318882, 88428.17629657475],
  [1764010857631, 88599.03241522705],
  [1764014484461, 88356.83122629141],
  [1764018104944, 89111.75024576523],
  [1764021710553, 88749.78735098541],
  [1764025262805, 88631.71085966966],
  [1764028887963, 88229.35740719768],
  [1764032503710, 88139.41175889166],
  [1764036041477, 87829.57652809896],
  [1764039616508, 87759.23926010152],
  [1764043307150, 87710.53378537255],
  [1764046885635, 88416.26556192817],
  [1764050472025, 88100.74473486726],
  [1764054147622, 87851.67691247856],
  [1764057661499, 87385.4867712119],
  [1764061352264, 87126.88420569089],
  [1764064971850, 87035.34816069364],
  [1764068634730, 87349.3248932984],
  [1764072107714, 87368.70154934759],
  [1764075652534, 87488.65596440769],
  [1764079313066, 86898.36528137974],
  [1764082932298, 86396.68263644705],
  [1764086442786, 86910.96082919533],
  [1764090099085, 87078.39643422313],
  [1764094075357, 87515.4235640805],
  [1764097376100, 87228.88735414941],
  [1764100970689, 86826.83681405816],
  [1764104475929, 87340.34991860151],
  [1764108065601, 86978.09855205339],
  [1764111670540, 87594.72411303585],
  [1764115239104, 87310.33159950442],
  [1764118939920, 87519.74766739071],
  [1764122537495, 87884.060172756],
  [1764126104287, 87758.1678796271],
  [1764129708266, 87091.71946980437],
  [1764133331688, 87198.0485583665],
  [1764136908895, 87533.46385277133],
  [1764140508642, 87794.92494380343],
  [1764144055607, 87888.58561715245],
  [1764147665284, 87388.00383293368],
  [1764151311826, 86805.57291021988],
  [1764154918890, 86942.3183287508],
  [1764158521534, 87016.31004378395],
  [1764162129436, 86597.45451490527],
  [1764165746538, 87032.2237573809],
  [1764169309916, 86938.44033179866],
  [1764172861256, 86900.39403850977],
  [1764176469751, 87816.9620054015],
  [1764180133829, 89679.636920768],
  [1764183800062, 90135.4617095681],
  [1764187324772, 89974.73440191097],
  [1764190889470, 89892.71151639915],
  [1764194469927, 90177.58874212035],
  [1764198103915, 90249.96897580565],
  [1764201729946, 90474.22677969698],
  [1764205245907, 90443.99930725468],
  [1764208910868, 90672.63665569115],
  [1764212535498, 91587.21677348937],
  [1764216197999, 91164.97533596179],
  [1764219691668, 91263.33732195737],
  [1764223313908, 90939.97388637412],
  [1764226950301, 91200.42621055408],
  [1764230465939, 91381.43807412974],
  [1764234178443, 91478.05273667352],
  [1764237694794, 91576.58973024273],
  [1764241270942, 91598.34021650812],
  [1764244887618, 91376.7077706091],
  [1764248486413, 90987.79712414106],
  [1764252138440, 90905.09240108743],
  [1764255712040, 90761.6833187102],
  [1764259239642, 90920.42601556465],
  [1764262908552, 91459.50551449621],
  [1764266544545, 91442.5470438727],
  [1764270103947, 91804.82094206505],
  [1764273717317, 91539.36768049354],
  [1764277305196, 91485.68637120655],
  [1764280814712, 91473.72674753252],
  [1764284434704, 91312.76899397155],
  [1764288073163, 91323.62827620257],
  [1764291718919, 91132.0278089504],
  [1764295361847, 90811.0714191063],
  [1764298924520, 91023.52004227442],
  [1764302463955, 91194.97100263558],
  [1764306115792, 91427.07002902139],
  [1764309676678, 91622.80614870525],
  [1764313318028, 91357.40418771433],
  [1764316921491, 90914.78541547488],
  [1764320553265, 91586.77543014655],
  [1764324190952, 91575.0569979346],
  [1764327696400, 91827.76941884054],
  [1764331339431, 91427.29692487956],
  [1764334873588, 91501.38254936752],
  [1764338761282, 92329.75218670673],
  [1764342078451, 92202.8635352892],
  [1764345695528, 92346.3518191028],
  [1764349311063, 90916.07081958275],
  [1764352897424, 90669.96401023648],
  [1764356530825, 90875.03116346477],
  [1764360182641, 91073.47626876217],
  [1764363703307, 91214.6778806227],
  [1764367313561, 91004.2467183952],
  [1764370929984, 91127.20612080491],
  [1764374497178, 90904.86767344689],
  [1764378120929, 90915.53889060777],
  [1764381619772, 90903.54544934392],
  [1764385287036, 90729.94558372116],
  [1764388883791, 90703.32205961774],
  [1764392462393, 90832.40522733841],
  [1764396158222, 90760.43415099659],
  [1764399658964, 90577.3016032145],
  [1764403267404, 90566.64547606678],
  [1764406944687, 90656.69077727084],
  [1764410528002, 90570.83431220289],
  [1764414142577, 90570.90074621874],
  [1764417719610, 90682.38876677728],
  [1764421302166, 90643.83762875079],
  [1764424884062, 90792.77747104311],
  [1764428529359, 90657.75590554604],
  [1764432087794, 91040.54640850973],
  [1764435722061, 91010.85460130044],
  [1764439202821, 90475.97662592627],
  [1764442914879, 90712.0028373462],
  [1764446421637, 90673.14817788692],
  [1764450108862, 90947.02454728537],
  [1764453714826, 91032.09673034618],
  [1764457263292, 90788.7597853794],
  [1764460904728, 90841.45258193677],
  [1764464526184, 90869.67603539713],
  [1764468097489, 90938.30683585707],
  [1764471703000, 90802.75505671403],
  [1764475307175, 90892.89987772267],
  [1764478902096, 90858.18783526495],
  [1764482506889, 90820.86657093189],
  [1764486101799, 90901.61050740648],
  [1764489666347, 90980.08369172398],
  [1764493311376, 91245.5298446914],
  [1764496866931, 91415.59812963865],
  [1764500507011, 91250.35811895505],
  [1764504115749, 91080.50963597072],
  [1764507611810, 91435.84477550915],
  [1764511563272, 91751.81702045338],
  [1764514922364, 91446.98814551288],
  [1764518509199, 91475.5890645801],
  [1764522118700, 91814.62353308922],
  [1764525692808, 91477.54598695686],
  [1764529315204, 91455.11137688499],
  [1764533191758, 91440.20549816827],
  [1764536505616, 91314.55693607975],
  [1764540089125, 91176.29202753108],
  [1764543705777, 91159.28211972128],
  [1764547297764, 90359.86873169734],
  [1764550823675, 87107.57804601092],
  [1764554493706, 87209.3202760441],
  [1764558116141, 86607.95806802201],
  [1764561672491, 86347.62398034424],
  [1764565283532, 85788.16096067103],
  [1764568909854, 85996.54791593562],
  [1764572576393, 86248.96829120435],
  [1764576076362, 86509.66964426964],
  [1764579694825, 86828.86588088673],
  [1764583276412, 86711.05550833189],
  [1764586898712, 86632.27972318193],
  [1764590625462, 86262.5310475135],
  [1764594066990, 85452.87201488385],
  [1764598007840, 85992.51478024718],
  [1764601315257, 86023.91194853347],
  [1764604821331, 84634.95418600549],
  [1764608504924, 84553.51608407828],
  [1764612047718, 84958.90011684994],
  [1764615726827, 85230.8975559526],
  [1764619212109, 85003.07161606019],
  [1764622933587, 85607.92665356252],
  [1764626499818, 86425.82291576332],
  [1764630100182, 86642.17601166596],
  [1764633707684, 86281.49519776918],
  [1764637341034, 86589.01329234689],
  [1764640869099, 86431.01161842069],
  [1764644541690, 86639.7190996139],
  [1764648078699, 86979.2416342632],
  [1764651694649, 86999.26753257588],
  [1764655334566, 87009.82948356986],
  [1764658893107, 87094.35617736231],
  [1764662459743, 87032.32838561568],
  [1764666012435, 86418.6233251056],
  [1764669713811, 86789.61201168034],
  [1764673351516, 87283.4200046968],
  [1764676937206, 87372.145785899],
  [1764680558215, 87310.28717151324],
  [1764684068949, 87676.27574943205],
  [1764687666824, 89212.56733407508],
  [1764691277240, 90929.17033076797],
  [1764694927535, 90988.35289671065],
  [1764698555335, 91516.49010026302],
  [1764702168191, 92003.14962051474],
  [1764705778455, 91925.7686665393],
  [1764709311279, 91006.60257571642],
  [1764712897541, 91642.26634875845],
  [1764716505274, 91972.84712515515],
  [1764720076399, 91320.07942505727],
  [1764723650153, 91587.10768114813],
  [1764727533767, 92305.80571530102],
  [1764730838985, 92804.99277281489],
  [1764734420628, 92694.94244803755],
  [1764738133476, 93148.20270941404],
  [1764741788955, 93673.50779118965],
  [1764745356554, 93405.41156538975],
  [1764748835695, 92997.38296608128],
  [1764752484321, 92758.94715524407],
  [1764756386703, 93187.76365353932],
  [1764759735401, 92967.95172916472],
  [1764763253482, 93014.56287493998],
  [1764766912008, 92955.9934046737],
  [1764770463337, 93155.5710477267],
  [1764774162538, 92689.18467540754],
  [1764777729138, 92462.71285159403],
  [1764781358528, 92358.91089703525],
  [1764784914395, 92991.34046933519],
  [1764788573801, 92701.01925701783],
  [1764792068543, 93042.76426891205],
  [1764795708440, 92956.21718894965],
  [1764799379991, 93748.59078386276],
  [1764802902091, 93717.47149577878],
  [1764806533682, 93428.59451478458],
  [1764810164145, 93035.40920589627],
  [1764813670218, 93194.86563225763],
  [1764817305381, 93855.83582607246],
  [1764820904054, 93567.32981233204],
  [1764824493072, 93361.27533623583],
  [1764828374677, 92899.65881208924],
  [1764831708719, 93124.7224503544],
  [1764835343988, 93344.22464629909],
  [1764838894711, 93162.29916189116],
  [1764842492986, 93576.35582972465],
  [1764846128691, 93249.89554012878],
  [1764849618335, 92962.28988355577],
  [1764853258908, 92982.88944879391],
  [1764856870979, 92532.02394137291],
  [1764860517163, 92053.41845475078],
  [1764864452213, 92596.47508142228],
  [1764867711697, 92349.10012511045],
  [1764871248732, 92448.2278390964],
  [1764874977985, 92131.16632716786],
  [1764878531355, 92068.62882915599],
  [1764882355025, 92469.36285556007],
  [1764885705555, 92194.78324592086],
  [1764889314467, 92349.58095934307],
  [1764892888700, 92140.70419795791],
  [1764896564556, 92302.08974651141],
  [1764900024240, 92370.2072229294],
  [1764903659890, 92527.8315926902],
  [1764907336561, 92302.35560866309],
  [1764910896095, 92070.48457147281],
  [1764914501648, 91921.18210371182],
  [1764918170626, 92263.3299565551],
  [1764921619262, 92244.84957275762],
  [1764925263257, 92114.99015350078],
  [1764928937442, 91133.25125696731],
  [1764932426109, 91321.13588701593],
  [1764936024719, 91367.32047901883],
  [1764939662449, 91261.71327040567],
  [1764943285252, 90495.89880179014],
  [1764946931353, 90239.62309417447],
  [1764950506410, 90691.05834616034],
  [1764954074639, 88838.81256963374],
  [1764957665872, 89320.67330009381],
  [1764961414597, 88971.13700892155],
  [1764964888699, 89661.0097557126],
  [1764968427157, 89319.18628091525],
  [1764972100516, 89168.6188930498],
  [1764975693417, 89246.76255414792],
  [1764979303734, 89307.09154512963],
  [1764982901025, 89411.87151142707],
  [1764986415183, 89313.00635292601],
  [1764990092273, 89404.64876063257],
  [1764993727039, 89659.75706048295],
  [1764997277817, 89670.35753876393],
  [1765001218673, 89596.5402589313],
  [1765004544417, 89700.0501824711],
  [1765008064718, 89610.67940053929],
  [1765011695681, 89322.01341173225],
  [1765015262581, 89590.58493068343],
  [1765018920827, 89523.29215522746],
  [1765022508562, 89626.21664015269],
  [1765026071708, 89598.52998975923],
  [1765029701728, 89686.06129936306],
  [1765033224014, 90081.81117280423],
  [1765036917330, 89791.26875713006],
  [1765040484067, 89711.11278041216],
  [1765044113406, 89688.726231859],
  [1765047735069, 89594.48934194396],
  [1765051329905, 89463.06998584204],
  [1765054882484, 89554.86879282963],
  [1765058509075, 89447.79992594938],
  [1765062098279, 89301.79183131723],
  [1765065674648, 89244.7620814118],
  [1765069257104, 89442.08598085925],
  [1765072861556, 89380.5784461144],
  [1765076516134, 89591.40163921085],
  [1765080071961, 89728.67942532501],
  [1765083666400, 89553.15476748442],
  [1765087289536, 89501.47167967241],
  [1765090891831, 89592.78832989243],
  [1765094453120, 89375.83415426753],
  [1765098121555, 89428.99362624755],
  [1765101672039, 89125.8674744549],
  [1765105255755, 89260.10758592366],
  [1765108877050, 89179.22240236348],
  [1765112512508, 89481.7211308164],
  [1765116159633, 89062.22627235795],
  [1765119738170, 88202.39414470572],
  [1765123233817, 89472.58036849847],
  [1765126859139, 89818.66878296863],
  [1765130475102, 90871.38352473611],
  [1765134350907, 91404.6679612346],
  [1765137687666, 91348.91857747045],
  [1765141292523, 91432.38872266383],
  [1765144892016, 90017.8399930689],
  [1765148496175, 89669.56280777082],
  [1765152049857, 90398.44875659449],
  [1765155707680, 90404.72666612809],
  [1765159290692, 91117.21836182859],
  [1765162924445, 91393.1884031835],
  [1765166507746, 91038.85575701772],
  [1765170092340, 91221.02400236895],
  [1765173690574, 91327.40930587606],
  [1765177300438, 91579.98599855526],
  [1765180860775, 91541.15536000222],
  [1765184493077, 91856.52696684626],
  [1765188087321, 91919.1147204135],
  [1765191676972, 92130.30140568635],
  [1765195304707, 91970.39918188896],
  [1765198916052, 91773.79233492597],
  [1765202437850, 91534.86023966796],
  [1765206078255, 90883.16143531555],
  [1765209723117, 90114.80515515296],
  [1765213326871, 89841.06111713321],
  [1765216896727, 90001.43020668387],
  [1765220518786, 89888.90896735874],
  [1765224111985, 90295.90375895712],
  [1765227669585, 90774.3775809705],
  [1765231262929, 91353.07766391555],
  [1765234909375, 90858.05062091617],
  [1765238502205, 90626.03734312119],
  [1765242082355, 90402.40253959721],
  [1765245693183, 90059.53846828423],
  [1765249346706, 90153.53918752559],
  [1765252890916, 90420.21548510875],
  [1765256544313, 89908.32646008272],
  [1765260094595, 89923.04989704031],
  [1765263718373, 90178.84633445465],
  [1765267295461, 90482.4862936932],
  [1765271170809, 90479.43467161931],
  [1765274519027, 90171.74987695283],
  [1765278029069, 90245.23997652612],
  [1765281798812, 90398.45972205752],
  [1765285395940, 90550.60274621374],
  [1765288904366, 90451.2816787047],
  [1765292426130, 90284.16136437163],
  [1765296462084, 93103.98634687548],
  [1765299744022, 94267.1832941627],
  [1765303299216, 93920.90473522742],
  [1765306897270, 93920.23589966235],
  [1765310508867, 93881.98556269355],
  [1765314095237, 93065.23177559406],
  [1765317697793, 92711.39528114548],
  [1765321322644, 92790.20448989807],
  [1765324872854, 92686.10402025313],
  [1765328501753, 92157.39293716304],
  [1765332011923, 92324.90446978032],
  [1765335688899, 92484.68449061408],
  [1765339297572, 92410.12951343387],
  [1765342890545, 92532.04126979447],
  [1765346498151, 92589.68700272198],
  [1765350063886, 92688.72784020523],
  [1765353695483, 92700.84237056004],
  [1765357285047, 92623.70256256762],
  [1765360906052, 92865.55966048971],
  [1765364505771, 92302.24850832098],
  [1765368103916, 92098.54214403489],
  [1765371716907, 91971.47016600415],
  [1765375293382, 92066.23910408375],
  [1765378897704, 91801.71806295244],
  [1765382490015, 91925.01301901884],
  [1765386081633, 92161.83427424994],
  [1765389697852, 92359.13258502026],
  [1765393299767, 92452.98824422824],
  [1765396902095, 92991.94802108228],
  [1765400499593, 92571.34583235167],
  [1765404100063, 92378.76809342115],
  [1765407700421, 92541.97526271449],
  [1765411221061, 92005.13714957413],
  [1765415199611, 91234.35089361278],
  [1765418514189, 90581.63312349115],
  [1765422173464, 90010.47516574137],
  [1765425712380, 89847.74904390301],
  [1765429228798, 90429.2959710253],
  [1765432980221, 90326.58067449176],
  [1765436465807, 90297.96444701945],
  [1765440093924, 90254.79657357016],
  [1765443608367, 90177.630745499],
  [1765447374898, 90261.28377800956],
  [1765450963077, 90311.07465277931],
  [1765454575827, 90243.1997213647],
  [1765458106647, 90150.50776909872],
  [1765461689451, 90140.72165136607],
  [1765465335771, 89463.2323445275],
  [1765468883402, 89858.098998661],
  [1765472506351, 89798.28032192719],
  [1765476149061, 89963.24823227283],
  [1765479738529, 90606.41419222065],
  [1765483342598, 90856.50878419071],
  [1765486813837, 91654.63656934419],
  [1765490620319, 93042.43802644171],
  [1765494012162, 92243.5394501412],
  [1765497833581, 92494.17691640415],
  [1765501253750, 92136.1782605738],
  [1765504951118, 92191.92871455324],
  [1765508516702, 92584.46652311603],
  [1765512086378, 92300.73489951616],
  [1765515704839, 92409.3679774134],
  [1765519249870, 92418.10102035834],
  [1765522869962, 92520.5820421584],
  [1765526445769, 92446.83415918204],
  [1765530128495, 92265.0009989212],
  [1765533777305, 92391.9395663188],
  [1765537336055, 92414.52820402496],
  [1765540890832, 92405.03428877179],
  [1765544610826, 92396.63341482232],
  [1765548460104, 92280.6327385549],
  [1765551714480, 92510.954770233],
  [1765555256289, 89947.35621835101],
  [1765559003124, 90084.0887493541],
  [1765562560434, 90045.02162170896],
  [1765566087787, 90587.53931965493],
  [1765569702383, 90195.2534824437],
  [1765573356187, 90300.35604485389],
  [1765576964517, 90216.45117344358],
  [1765580483854, 90323.07179560265],
  [1765584099328, 90307.26028567803],
  [1765587647071, 90333.80918947668],
  [1765591268648, 90219.70368191416],
  [1765594849531, 90233.36847229167],
  [1765598474064, 90362.49787361179],
  [1765602357196, 90366.89143832374],
  [1765605709545, 90284.22919509024],
  [1765609235429, 90358.63720040456],
  [1765612913627, 90332.54808133405],
  [1765616505544, 90474.25879335239],
  [1765620068351, 90413.90012203652],
  [1765623702514, 90601.31912456751],
  [1765627309210, 90350.91781562121],
  [1765630914097, 90312.09050290582],
  [1765634509734, 90256.14764610285],
  [1765638088897, 90105.01414762474],
  [1765641676400, 90097.46740622642],
  [1765645591024, 90095.94884790409],
  [1765648915830, 90056.9602943351],
  [1765652579124, 90119.90143464747],
  [1765656026103, 90189.90865634271],
  [1765659730108, 90132.23549524162],
  [1765663338184, 90067.13467142553],
  [1765666903129, 90170.685696021],
  [1765670492860, 90253.11813342397],
  [1765674080895, 90357.27452201652],
  [1765677661669, 90298.00793502598],
  [1765681303383, 90288.06549056442],
  [1765684933877, 90251.74050833493],
  [1765688467035, 90202.89925881376],
  [1765692071252, 90195.39829927523],
  [1765695621485, 90151.98318157879],
  [1765699260704, 90235.19014847181],
  [1765702927743, 90161.59120299897],
  [1765706511217, 90023.43917813247],
  [1765710075619, 89840.80964857385],
  [1765713738641, 89231.74542159855],
  [1765717363780, 89395.70903561803],
  [1765720801152, 89311.27541342899],
  [1765724495821, 89020.13114083151],
  [1765728071440, 89009.25981262162],
  [1765731757671, 88809.76576919208],
  [1765735297774, 88809.27700826648],
  [1765738917631, 88998.90781774413],
  [1765742496503, 88674.60117447103],
  [1765746049250, 88577.56241554697],
  [1765749686143, 88477.2989237882],
  [1765753305862, 88291.27423697856],
  [1765756889362, 88230.77409367911],
  [1765760480018, 88488.55514914883],
  [1765764092531, 89274.74658721793],
  [1765767833222, 89310.04361576558],
  [1765771270194, 89297.3727219714],
  [1765774907964, 89668.13527779233],
  [1765778510108, 89564.69022439446],
  [1765782197296, 89811.24061072449],
  [1765785803068, 89714.60638590455],
  [1765789362706, 89794.92174069313],
  [1765792907260, 89867.63967629262],
  [1765796432016, 89869.01773202233],
  [1765800077798, 89640.50135204557],
  [1765803706295, 89699.67091524602],
  [1765807388387, 89438.97307941841],
  [1765810906928, 87975.78932131453],
  [1765814589153, 86944.63604570336],
  [1765818105160, 86376.50299974006],
  [1765821669866, 85704.70802098143],
  [1765825324184, 86173.54692397923],
  [1765828958765, 86025.87478170796],
  [1765832509255, 85803.51861744869],
  [1765836071794, 86217.69481699889],
  [1765839677964, 86115.3087389092],
  [1765843306712, 86413.22138097929],
  [1765846918220, 85814.24822225161],
  [1765850465770, 85900.22101168243],
  [1765854105365, 85950.10854836363],
  [1765857703733, 85848.70319000457],
  [1765861305405, 85830.92653857765],
  [1765864926263, 86036.81198662342],
  [1765868577482, 86515.59449042796],
  [1765872041348, 86036.32380994338],
  [1765876044381, 86243.71038076178],
  [1765879307278, 86305.28532317241],
  [1765882975653, 86969.77661275564],

In [5]:
import pandas as pd
data = pd.DataFrame(bitcoin_data['prices'], columns=['TimeStamp','Price'])
data

         TimeStamp         Price
0    1763985712847  86268.293366
1    1763989255710  85957.054085
2    1763992837688  86269.665652
3    1763996558643  86192.311605
4    1764000097296  86425.727452
..             ...           ...
716  1766563229475  86897.938847
717  1766566832366  86744.954395
718  1766570410304  86755.271576
719  1766574083760  87032.387404
720  1766576131000  87180.104502

[721 rows x 2 columns]

In [8]:
data['Date'] = pd.to_datetime(data['TimeStamp'], unit = 'ms')
data

         TimeStamp         Price                    Date
0    1763985712847  86268.293366 2025-11-24 12:01:52.847
1    1763989255710  85957.054085 2025-11-24 13:00:55.710
2    1763992837688  86269.665652 2025-11-24 14:00:37.688
3    1763996558643  86192.311605 2025-11-24 15:02:38.643
4    1764000097296  86425.727452 2025-11-24 16:01:37.296
..             ...           ...                     ...
716  1766563229475  86897.938847 2025-12-24 08:00:29.475
717  1766566832366  86744.954395 2025-12-24 09:00:32.366
718  1766570410304  86755.271576 2025-12-24 10:00:10.304
719  1766574083760  87032.387404 2025-12-24 11:01:23.760
720  1766576131000  87180.104502 2025-12-24 11:35:31.000

[721 rows x 3 columns]

In [12]:
candlstick_data = data.groupby(data.Date.dt.date).agg({'Price':['min','max','first','last']})
candlstick_data

                   Price
                     min           max         first          last
Date
2025-11-24  85957.054085  89111.750246  86268.293366  88631.710860
2025-11-25  86396.682636  88416.265562  88229.357407  87594.724113
2025-11-26  86597.454515  90249.968976  87310.331600  90249.968976
2025-11-27  90443.999307  91804.820942  90474.226780  91312.768994
2025-11-28  90669.964010  92346.351819  91323.628276  91127.206121
2025-11-29  90475.976626  91040.546409  90904.867673  90788.759785
2025-11-30  90802.755057  91814.623533  90841.452582  91159.282120
2025-12-01  84553.516084  90359.868732  90359.868732  86642.176012
2025-12-02  86281.495198  92003.149621  86281.495198  91972.847125
2025-12-03  91320.079425  93748.590784  91320.079425  93717.471496
2025-12-04  92053.418455  93855.835826  93428.594515  92349.580959
2025-12-05  88838.812570  92527.831593  92140.704198  89246.762554
2025-12-06  89301.791831  90081.811173  89307.091545  89301.791831
2025-12-07  88202.394145  91432.388723  89244.762081  89669.562808
2025-12-08  89841.061117  92130.301406  90398.448757  90858.050621
2025-12-09  89908.326460  94267.183294  90626.037343  92790.204490
2025-12-10  91801.718063  92991.948021  92686.104020  92541.975263
2025-12-11  89463.232345  93042.438026  92005.137150  92243.539450
2025-12-12  89947.356218  92584.466523  92494.176916  90323.071796
2025-12-13  90056.960294  90601.319125  90307.260286  90170.685696
2025-12-14  88291.274237  90357.274522  90253.118133  88291.274237
2025-12-15  85704.708021  89869.017732  88230.774094  86115.308739
2025-12-16  85814.248222  87882.794941  86413.221381  87752.713630
2025-12-17  85809.173382  89605.992064  87719.681398  86219.031756
2025-12-18  84581.283372  88864.613645  86196.821373  85515.311331
2025-12-19  85260.287357  88241.702079  85450.331201  88241.702079
2025-12-20  87944.878879  88288.458464  88103.860757  88288.458464
2025-12-21  87655.164185  88948.664173  88347.943106  88466.393369
2025-12-22  88035.955550  90168.944487  88672.329679  88604.745049
2025-12-23  87152.736287  88741.538473  88491.120208  87350.516062
2025-12-24  86744.954395  87576.756383  87496.146692  87180.104502

In [14]:
import plotly.graph_objects as go
import plotly.offline as pyo

fig = go.Figure(
    data=[
        go.Candlestick(
            x=candlstick_data.index,
            open=candlstick_data['Price']['first'],
            high=candlstick_data['Price']['max'],
            low=candlstick_data['Price']['min'],
            close=candlstick_data['Price']['last']
        )
    ]
)

fig.update_layout(
    xaxis_rangeslider_visible=False,
    xaxis_title='Date',
    yaxis_title='Price (USD $)',
    title='Bitcoin Candlestick Chart Over Past 30 Days'
)

pyo.plot(
    fig,
    filename='./bitcoin_candlestick_graph.html',
    auto_open=False
)

'./bitcoin_candlestick_graph.html'