#   LAB M5_4: API Examples 
### (RandomUser API - https://randomuser.me/documentation
### Fruityvice API  - https://www.fruityvice.com/
### Open-Joke-API   - https://official-joke-api.appspot.com/jokes/ten
##  Author  : LiR
### Date    : 28-12-2025

In [1]:
!pip install randomuser
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py): started
  Building wheel for randomuser (setup.py): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5128 sha256=3cec2507314f18f4d3bcd70695dfd7c3b56fb4e7816c7d9031d56043a431debf
  Stored in directory: c:\users\rusla\appdata\local\pip\cache\wheels\fc\8d\74\bcdd5e8a9433bfa4c4f9c1cccbfec40139322a28d77f61e45e
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

  DEPRECATION: Building 'randomuser' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'randomuser'. Discussion can be found at https://github.com/pypa/pip/issues/6334

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\dev_soft\anaconda3_2023\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\rusla\appdata\roaming\python\python311\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\dev_soft\anaconda3_2023\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\dev_soft\anaconda3_2023\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\dev_soft\anaconda3_2023\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\dev_soft\anaconda3_2023\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
from randomuser import RandomUser
import pandas as pd

In [3]:
r = RandomUser()

In [10]:
some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x1873be45990>,
 <randomuser.RandomUser at 0x1873be459d0>,
 <randomuser.RandomUser at 0x1873be45a10>,
 <randomuser.RandomUser at 0x1873be45a50>,
 <randomuser.RandomUser at 0x1873be45a90>,
 <randomuser.RandomUser at 0x1873be45b10>,
 <randomuser.RandomUser at 0x1873be45b50>,
 <randomuser.RandomUser at 0x1873be45b90>,
 <randomuser.RandomUser at 0x1873be45bd0>,
 <randomuser.RandomUser at 0x1873be45ad0>]

In [7]:
Name = r.get_full_name()
Name

'Ege Gürmen'

In [13]:
for user in some_list:
    print ( " ",user.get_full_name(),"            ",user.get_email())

  Encarnacion Velasco              encarnacion.velasco@example.com
  Luisa Ramos              luisa.ramos@example.com
  رها محمدخان              rh.mhmdkhn@example.com
  Étienne Menard              etienne.menard@example.com
  Barb Reid              barb.reid@example.com
  Liciniano da Cunha              liciniano.dacunha@example.com
  Noah Poulsen              noah.poulsen@example.com
  Nela Bjørk              nela.bjork@example.com
  Neea Halko              neea.halko@example.com
  Becky Simmmons              becky.simmmons@example.com

In [14]:
#Exercise 1 In this Exercise, generate photos of the random 10 users.
for user in some_list:
    print ( user.get_picture(), " ",user.get_full_name(),"            ",user.get_email())

https://randomuser.me/api/portraits/women/22.jpg   Encarnacion Velasco              encarnacion.velasco@example.com
https://randomuser.me/api/portraits/women/90.jpg   Luisa Ramos              luisa.ramos@example.com
https://randomuser.me/api/portraits/women/80.jpg   رها محمدخان              rh.mhmdkhn@example.com
https://randomuser.me/api/portraits/men/24.jpg   Étienne Menard              etienne.menard@example.com
https://randomuser.me/api/portraits/women/49.jpg   Barb Reid              barb.reid@example.com
https://randomuser.me/api/portraits/men/5.jpg   Liciniano da Cunha              liciniano.dacunha@example.com
https://randomuser.me/api/portraits/men/57.jpg   Noah Poulsen              noah.poulsen@example.com
https://randomuser.me/api/portraits/women/66.jpg   Nela Bjørk              nela.bjork@example.com
https://randomuser.me/api/portraits/women/47.jpg   Neea Halko              neea.halko@example.com
https://randomuser.me/api/portraits/women/23.jpg   Becky Simmmons              becky.simmmons@example.com

In [19]:
#To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.
def get_users():
    list_users =[]
     
    for user in RandomUser.generate_users(10):
        list_users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(list_users) 
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,مهدیس موسوی,female,ورامین,آذربایجان غربی,mhdys.mwswy@example.com,1962-04-15T13:28:15.616Z,https://randomuser.me/api/portraits/women/20.jpg
1,Hagen Hollstein,male,Herbolzheim,Baden-Württemberg,hagen.hollstein@example.com,1993-01-27T09:29:11.238Z,https://randomuser.me/api/portraits/men/25.jpg
2,Luigi Bohne,male,Heideck,Sachsen,luigi.bohne@example.com,1948-06-06T03:26:33.614Z,https://randomuser.me/api/portraits/men/2.jpg
3,Kasper Hatala,male,Taipalsaari,Lapland,kasper.hatala@example.com,1990-04-04T13:59:13.206Z,https://randomuser.me/api/portraits/men/72.jpg
4,Aldo Leber,male,Stadtilm,Berlin,aldo.leber@example.com,1978-09-24T14:50:42.451Z,https://randomuser.me/api/portraits/men/21.jpg
5,Nikolaj Petersen,male,Nr Åby,Syddanmark,nikolaj.petersen@example.com,1957-11-11T15:18:50.052Z,https://randomuser.me/api/portraits/men/72.jpg
6,Lucia Lopez,female,Cuenca,Andalucía,lucia.lopez@example.com,1949-08-04T08:20:00.388Z,https://randomuser.me/api/portraits/women/4.jpg
7,Naoufal Van der Meijs,male,Nieuwebrug,Flevoland,naoufal.vandermeijs@example.com,1970-07-29T00:47:00.627Z,https://randomuser.me/api/portraits/men/87.jpg
8,Angel Moore,male,Naas,South Dublin,angel.moore@example.com,1962-03-30T06:54:49.672Z,https://randomuser.me/api/portraits/men/99.jpg
9,Leevi Toivonen,male,Rauma,Southern Savonia,leevi.toivonen@example.com,1990-08-25T19:40:38.238Z,https://randomuser.me/api/portraits/men/21.jpg

In [18]:
df1 = pd.DataFrame(get_users())

In [32]:
#Example 2: Fruityvice API
import requests
import json
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")
results = json.loads(data.text)
print(results)
my_df = pd.DataFrame(results)
print(my_df)
df2 = pd.json_normalize(results)
df2

[{'name': 'Persimmon', 'id': 52, 'family': 'Ebenaceae', 'order': 'Rosales', 'genus': 'Diospyros', 'nutritions': {'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'carbohydrates': 18.0, 'protein': 0.0}}, {'name': 'Strawberry', 'id': 3, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Fragaria', 'nutritions': {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'carbohydrates': 5.5, 'protein': 0.8}}, {'name': 'Banana', 'id': 1, 'family': 'Musaceae', 'order': 'Zingiberales', 'genus': 'Musa', 'nutritions': {'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'carbohydrates': 22.0, 'protein': 1.0}}, {'name': 'Tomato', 'id': 5, 'family': 'Solanaceae', 'order': 'Solanales', 'genus': 'Solanum', 'nutritions': {'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'carbohydrates': 3.9, 'protein': 0.9}}, {'name': 'Pear', 'id': 4, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Pyrus', 'nutritions': {'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'carbohydrates': 15.0, 'protein': 0.4}}, {'name': 'Durian', 'id': 60, 'family': 'Malvaceae', 'order': 'Malvales', 'genus': 'Durio', 'nutritions': {'calories': 147, 'fat': 5.3, 'sugar': 6.75, 'carbohydrates': 27.1, 'protein': 1.5}}, {'name': 'Blackberry', 'id': 64, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Rubus', 'nutritions': {'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'carbohydrates': 9.0, 'protein': 1.3}}, {'name': 'Lingonberry', 'id': 65, 'family': 'Ericaceae', 'order': 'Ericales', 'genus': 'Vaccinium', 'nutritions': {'calories': 50, 'fat': 0.34, 'sugar': 5.74, 'carbohydrates': 11.3, 'protein': 0.75}}, {'name': 'Kiwi', 'id': 66, 'family': 'Actinidiaceae', 'order': 'Struthioniformes', 'genus': 'Apteryx', 'nutritions': {'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'carbohydrates': 15.0, 'protein': 1.1}}, {'name': 'Lychee', 'id': 67, 'family': 'Sapindaceae', 'order': 'Sapindales', 'genus': 'Litchi', 'nutritions': {'calories': 66, 'fat': 0.44, 'sugar': 15.0, 'carbohydrates': 17.0, 'protein': 0.8}}, {'name': 'Pineapple', 'id': 10, 'family': 'Bromeliaceae', 'order': 'Poales', 'genus': 'Ananas', 'nutritions': {'calories': 50, 'fat': 0.12, 'sugar': 9.85, 'carbohydrates': 13.12, 'protein': 0.54}}, {'name': 'Fig', 'id': 68, 'family': 'Moraceae', 'order': 'Rosales', 'genus': 'Ficus', 'nutritions': {'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'carbohydrates': 19.0, 'protein': 0.8}}, {'name': 'Gooseberry', 'id': 69, 'family': 'Grossulariaceae', 'order': 'Saxifragales', 'genus': 'Ribes', 'nutritions': {'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'carbohydrates': 10.0, 'protein': 0.9}}, {'name': 'Passionfruit', 'id': 70, 'family': 'Passifloraceae', 'order': 'Malpighiales', 'genus': 'Passiflora', 'nutritions': {'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'carbohydrates': 22.4, 'protein': 2.2}}, {'name': 'Plum', 'id': 71, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus', 'nutritions': {'calories': 46, 'fat': 0.28, 'sugar': 9.92, 'carbohydrates': 11.4, 'protein': 0.7}}, {'name': 'Orange', 'id': 2, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'carbohydrates': 8.3, 'protein': 1.0}}, {'name': 'GreenApple', 'id': 72, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Malus', 'nutritions': {'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'carbohydrates': 3.1, 'protein': 0.4}}, {'name': 'Raspberry', 'id': 23, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Rubus', 'nutritions': {'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'carbohydrates': 12.0, 'protein': 1.2}}, {'name': 'Watermelon', 'id': 25, 'family': 'Cucurbitaceae', 'order': 'Cucurbitales', 'genus': 'Citrullus', 'nutritions': {'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'carbohydrates': 8.0, 'protein': 0.6}}, {'name': 'Lemon', 'id': 26, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'carbohydrates': 9.0, 'protein': 1.1}}, {'name': 'Mango', 'id': 27, 'family': 'Anacardiaceae', 'order': 'Sapindales', 'genus': 'Mangifera', 'nutritions': {'calories': 60, 'fat': 0.38, 'sugar': 13.7, 'carbohydrates': 15.0, 'protein': 0.82}}, {'name': 'Blueberry', 'id': 33, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Fragaria', 'nutritions': {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'carbohydrates': 5.5, 'protein': 0.0}}, {'name': 'Apple', 'id': 6, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Malus', 'nutritions': {'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'carbohydrates': 11.4, 'protein': 0.3}}, {'name': 'Guava', 'id': 37, 'family': 'Myrtaceae', 'order': 'Myrtales', 'genus': 'Psidium', 'nutritions': {'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'carbohydrates': 14.0, 'protein': 2.6}}, {'name': 'Apricot', 'id': 35, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus', 'nutritions': {'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'carbohydrates': 3.9, 'protein': 0.5}}, {'name': 'Melon', 'id': 41, 'family': 'Cucurbitaceae', 'order': 'Cucurbitaceae', 'genus': 'Cucumis', 'nutritions': {'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'carbohydrates': 8.0, 'protein': 0.0}}, {'name': 'Tangerine', 'id': 77, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'carbohydrates': 8.3, 'protein': 0.0}}, {'name': 'Pitahaya', 'id': 78, 'family': 'Cactaceae', 'order': 'Caryophyllales', 'genus': 'Cactaceae', 'nutritions': {'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'carbohydrates': 7.0, 'protein': 1.0}}, {'name': 'Lime', 'id': 44, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'carbohydrates': 8.4, 'protein': 0.3}}, {'name': 'Pomegranate', 'id': 79, 'family': 'Lythraceae', 'order': 'Myrtales', 'genus': 'Punica', 'nutritions': {'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'carbohydrates': 18.7, 'protein': 1.7}}, {'name': 'Dragonfruit', 'id': 80, 'family': 'Cactaceae', 'order': 'Caryophyllales', 'genus': 'Selenicereus', 'nutritions': {'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'carbohydrates': 9.0, 'protein': 9.0}}, {'name': 'Grape', 'id': 81, 'family': 'Vitaceae', 'order': 'Vitales', 'genus': 'Vitis', 'nutritions': {'calories': 69, 'fat': 0.16, 'sugar': 16.0, 'carbohydrates': 18.1, 'protein': 0.72}}, {'name': 'Morus', 'id': 82, 'family': 'Moraceae', 'order': 'Rosales', 'genus': 'Morus', 'nutritions': {'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'carbohydrates': 9.8, 'protein': 1.44}}, {'name': 'Feijoa', 'id': 76, 'family': 'Myrtaceae', 'order': 'Myrtoideae', 'genus': 'Sellowiana', 'nutritions': {'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'carbohydrates': 8.0, 'protein': 0.6}}, {'name': 'Avocado', 'id': 84, 'family': 'Lauraceae', 'order': 'Laurales', 'genus': 'Persea', 'nutritions': {'calories': 160, 'fat': 14.66, 'sugar': 0.66, 'carbohydrates': 8.53, 'protein': 2.0}}, {'name': 'Kiwifruit', 'id': 85, 'family': 'Actinidiaceae', 'order': 'Ericales', 'genus': 'Actinidia', 'nutritions': {'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'carbohydrates': 14.6, 'protein': 1.14}}, {'name': 'Cranberry', 'id': 87, 'family': 'Ericaceae', 'order': 'Ericales', 'genus': 'Vaccinium', 'nutritions': {'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'carbohydrates': 12.2, 'protein': 0.4}}, {'name': 'Cherry', 'id': 9, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus', 'nutritions': {'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'carbohydrates': 12.0, 'protein': 1.0}}, {'name': 'Peach', 'id': 86, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus', 'nutritions': {'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'carbohydrates': 9.5, 'protein': 0.9}}, {'name': 'Jackfruit', 'id': 94, 'family': 'Moraceae', 'order': 'Rosales', 'genus': 'Artocarpus', 'nutritions': {'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'carbohydrates': 23.2, 'protein': 1.72}}, {'name': 'Horned Melon', 'id': 95, 'family': 'Cucurbitaceae', 'order': 'Cucurbitales', 'genus': 'Cucumis', 'nutritions': {'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'carbohydrates': 7.56, 'protein': 1.78}}, {'name': 'Hazelnut', 'id': 96, 'family': 'Betulaceae', 'order': 'Fagales', 'genus': 'Corylus', 'nutritions': {'calories': 628, 'fat': 61.0, 'sugar': 4.3, 'carbohydrates': 17.0, 'protein': 15.0}}, {'name': 'Pomelo', 'id': 98, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus', 'nutritions': {'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'carbohydrates': 9.67, 'protein': 0.82}}, {'name': 'Mangosteen', 'id': 99, 'family': 'Clusiaceae', 'order': 'Malpighiales', 'genus': 'Garcinia', 'nutritions': {'calories': 73, 'fat': 0.58, 'sugar': 16.11, 'carbohydrates': 17.91, 'protein': 0.41}}, {'name': 'Pumpkin', 'id': 100, 'family': 'Cucurbitaceae', 'order': 'Cucurbitales', 'genus': 'Cucurbita', 'nutritions': {'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'carbohydrates': 4.6, 'protein': 1.1}}, {'name': 'Japanese Persimmon', 'id': 101, 'family': ' Ebenaceae', 'order': ' Ericales', 'genus': 'Diospyros', 'nutritions': {'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'carbohydrates': 19.0, 'protein': 0.6}}, {'name': 'Papaya', 'id': 42, 'family': 'Caricaceae', 'order': 'Brassicales', 'genus': 'Carica', 'nutritions': {'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'carbohydrates': 5.8, 'protein': 0.5}}, {'name': 'Annona', 'id': 103, 'family': 'Annonaceae', 'order': 'Rosales', 'genus': 'Annonas', 'nutritions': {'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'carbohydrates': 19.1, 'protein': 1.5}}, {'name': 'Ceylon Gooseberry', 'id': 104, 'family': 'Salicaceae', 'order': 'Malpighiales', 'genus': 'Dovyalis', 'nutritions': {'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'carbohydrates': 9.6, 'protein': 1.2}}]
                  name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros
1           Strawberry    3         Rosaceae           Rosales      Fragaria
2               Banana    1         Musaceae      Zingiberales          Musa
3               Tomato    5       Solanaceae         Solanales       Solanum
4                 Pear    4         Rosaceae           Rosales         Pyrus
5               Durian   60        Malvaceae          Malvales         Durio
6           Blackberry   64         Rosaceae           Rosales         Rubus
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx
9               Lychee   67      Sapindaceae        Sapindales        Litchi
10           Pineapple   10     Bromeliaceae            Poales        Ananas
11                 Fig   68         Moraceae           Rosales         Ficus
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora
14                Plum   71         Rosaceae           Rosales        Prunus
15              Orange    2         Rutaceae        Sapindales        Citrus
16          GreenApple   72         Rosaceae           Rosales         Malus
17           Raspberry   23         Rosaceae           Rosales         Rubus
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus
19               Lemon   26         Rutaceae        Sapindales        Citrus
20               Mango   27    Anacardiaceae        Sapindales     Mangifera
21           Blueberry   33         Rosaceae           Rosales      Fragaria
22               Apple    6         Rosaceae           Rosales         Malus
23               Guava   37        Myrtaceae          Myrtales       Psidium
24             Apricot   35         Rosaceae           Rosales        Prunus
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis
26           Tangerine   77         Rutaceae        Sapindales        Citrus
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae
28                Lime   44         Rutaceae        Sapindales        Citrus
29         Pomegranate   79       Lythraceae          Myrtales        Punica
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus
31               Grape   81         Vitaceae           Vitales         Vitis
32               Morus   82         Moraceae           Rosales         Morus
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana
34             Avocado   84        Lauraceae          Laurales        Persea
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia
36           Cranberry   87        Ericaceae          Ericales     Vaccinium
37              Cherry    9         Rosaceae           Rosales        Prunus
38               Peach   86         Rosaceae           Rosales        Prunus
39           Jackfruit   94         Moraceae           Rosales    Artocarpus
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis
41            Hazelnut   96       Betulaceae           Fagales       Corylus
42              Pomelo   98         Rutaceae        Sapindales        Citrus
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros
46              Papaya   42       Caricaceae       Brassicales        Carica
47              Annona  103       Annonaceae           Rosales       Annonas
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis

                                           nutritions
0   {'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c...
1   {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca...
2   {'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c...
3   {'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca...
4   {'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c...
5   {'calories': 147, 'fat': 5.3, 'sugar': 6.75, '...
6   {'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca...
7   {'calories': 50, 'fat': 0.34, 'sugar': 5.74, '...
8   {'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca...
9   {'calories': 66, 'fat': 0.44, 'sugar': 15.0, '...
10  {'calories': 50, 'fat': 0.12, 'sugar': 9.85, '...
11  {'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c...
12  {'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca...
13  {'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c...
14  {'calories': 46, 'fat': 0.28, 'sugar': 9.92, '...
15  {'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca...
16  {'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca...
17  {'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca...
18  {'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca...
19  {'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca...
20  {'calories': 60, 'fat': 0.38, 'sugar': 13.7, '...
21  {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca...
22  {'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c...
23  {'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca...
24  {'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca...
25  {'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca...
26  {'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca...
27  {'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca...
28  {'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca...
29  {'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c...
30  {'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca...
31  {'calories': 69, 'fat': 0.16, 'sugar': 16.0, '...
32  {'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c...
33  {'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca...
34  {'calories': 160, 'fat': 14.66, 'sugar': 0.66,...
35  {'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca...
36  {'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca...
37  {'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca...
38  {'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c...
39  {'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c...
40  {'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c...
41  {'calories': 628, 'fat': 61.0, 'sugar': 4.3, '...
42  {'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca...
43  {'calories': 73, 'fat': 0.58, 'sugar': 16.11, ...
44  {'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca...
45  {'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c...
46  {'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca...
47  {'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c...
48  {'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca...

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

In [29]:
#Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.
cherry = df2.loc[df2["name"] == 'Cherry']
print((cherry.iloc[0]['family']) , (cherry.iloc[0]['genus']))
cherry

Rosaceae Prunus

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.3,8.0,12.0,1.0

In [84]:
#Double
duplicates  = list()
#print(len(df2.groupby(['name'])))
duplicates = df2['name'].value_counts()
duplicates = duplicates[duplicates == 1]
print(duplicates)

name
Persimmon             1
Strawberry            1
Banana                1
Tomato                1
Pear                  1
Durian                1
Blackberry            1
Lingonberry           1
Kiwi                  1
Lychee                1
Pineapple             1
Fig                   1
Gooseberry            1
Passionfruit          1
Plum                  1
Orange                1
GreenApple            1
Raspberry             1
Watermelon            1
Lemon                 1
Mango                 1
Blueberry             1
Apple                 1
Guava                 1
Apricot               1
Melon                 1
Tangerine             1
Pitahaya              1
Lime                  1
Pomegranate           1
Dragonfruit           1
Grape                 1
Morus                 1
Feijoa                1
Avocado               1
Kiwifruit             1
Cranberry             1
Cherry                1
Peach                 1
Jackfruit             1
Horned Melon          1
Hazelnut              1
Pomelo                1
Mangosteen            1
Pumpkin               1
Japanese Persimmon    1
Papaya                1
Annona                1
Ceylon Gooseberry     1
Name: count, dtype: int64

In [193]:
#Exercise 2
#In this Exercise, find out how many calories are contained in a banana.
df_banana = pd.DataFrame(df2.loc[df2['name'] == 'Banana'])
#print(df_banana)
res = (df_banana.iloc[0]['name'], df_banana.iloc[0]['nutritions.calories'])
print(res)

('Banana', np.int64(96))

In [ ]:
#Exercise 3:
# https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/
# This API returns random jokes from a database. The following URL can be used to retrieve 10 random jokes.
# https://official-joke-api.appspot.com/jokes/ten
import requests
# определить как читать
#------------text/html
url = 'https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/'
web_page_data = requests.get(url)
print(web_page_data.headers['Content-Type'])
#if web_page_data.status_code == 200:
#    print(27*'-',' web_page_data.text[0:100] :\n', web_page_data.text)
#----------------json
url = 'https://official-joke-api.appspot.com/jokes/ten'
web_page_data = requests.get(url)
print(web_page_data.headers['Content-Type'])

res = json.loads(web_page_data.text)
pd.DataFrame(res)

text/html; charset=UTF-8
application/json; charset=utf-8

,type,setup,punchline,id
0,general,How do you make a hankie dance?,Put a little boogie in it.,127
1,programming,Why did the developer go to therapy?,They had too many unresolved issues.,444
2,programming,Which song would an exception sing?,Can't catch me - Avicii,32
3,general,How do you fix a damaged jack-o-lantern?,You use a pumpkin patch.,123
4,general,Why didn’t the skeleton cross the road?,Because he had no guts.,339
5,general,What has ears but cannot hear?,A field of corn.,238
6,general,What is the difference between ignorance and a...,I don't know and I don't care.,244
7,general,What do you call a dictionary on drugs?,High definition.,199
8,general,Want to hear a chimney joke?,Got stacks of em! First one's on the house,150
9,general,What is red and smells like blue paint?,Red paint!,243

In [ ]:
df_jokers = pd.DataFrame(res)
#df_jokers
df_jokers.drop(columns=['type','id'], inplace=True) 
df_jokers

,setup,punchline
0,How do you make a hankie dance?,Put a little boogie in it.
1,Why did the developer go to therapy?,They had too many unresolved issues.
2,Which song would an exception sing?,Can't catch me - Avicii
3,How do you fix a damaged jack-o-lantern?,You use a pumpkin patch.
4,Why didn’t the skeleton cross the road?,Because he had no guts.
5,What has ears but cannot hear?,A field of corn.
6,What is the difference between ignorance and a...,I don't know and I don't care.
7,What do you call a dictionary on drugs?,High definition.
8,Want to hear a chimney joke?,Got stacks of em! First one's on the house
9,What is red and smells like blue paint?,Red paint!

In [ ]:
#read Big List of Free Open APIs
import pandas as pd
import requests

url = "https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/"

web_page_data = requests.get(url)
print(web_page_data.headers['Content-Type'])

tables = pd.read_html(url)
df_table = tables[0]   # READ FIRST TABLE FROM WEB
print(df_table.head())

text/html; charset=UTF-8
   #         CATEGORY                  API NAME                  DESCRIPTION  \
0  1  API Directories                 APIs.guru        OpenAPI API directory
1  2     Art & Images  Art Institute of Chicago      Artwork from the museum
2  3     Art & Images              COLOURlovers                 Color trends
3  4     Art & Images                  DiceBear  Generate random SVG avatars
4  5     Art & Images                      Dogs            Random dog images

                                          SAMPLE URL
0                 https://api.apis.guru/v2/list.json
1  https://api.artic.edu/api/v1/artworks/search?q...
2  https://www.colourlovers.com/api/colors/new?fo...
3         https://api.dicebear.com/6.x/pixel-art/svg
4            https://dog.ceo/api/breeds/image/random

In [ ]:
# READ FROM WEBsEIT
banana = {
    "name": "Banana",
    "id": 1,
    "family": "Musaceae",
    "order": "Zingiberales",
    "genus": "Musa",
    "nutritions": 
    {
    "calories": 96,
    "fat": 0.2,
    "sugar": 17.2,
    "carbohydrates": 22,
    "protein": 1
    }
}
df_b = pd.DataFrame(banana)
df_b

                 name  id    family         order genus  nutritions
calories       Banana   1  Musaceae  Zingiberales  Musa        96.0
fat            Banana   1  Musaceae  Zingiberales  Musa         0.2
sugar          Banana   1  Musaceae  Zingiberales  Musa        17.2
carbohydrates  Banana   1  Musaceae  Zingiberales  Musa        22.0
protein        Banana   1  Musaceae  Zingiberales  Musa         1.0